name: Laravel CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql/mysql-server:8.0
        env:
          MYSQL_ROOT_PASSWORD: password # You should replace this with a secure password or a GitHub secret
          MYSQL_DATABASE: your_database_name # Replace with your database name
        ports:
          - 3306:3306
        options: >-
          --health-cmd='mysqladmin ping --silent'
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      redis:
        image: redis:alpine
        ports:
          - 6379:6379

      # Add other services like MeiliSearch, Mailpit, Selenium, etc., as needed

    steps:
    - uses: actions/checkout@v2

    # Set up PHP
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, redis
        tools: composer:v2

    # Install PHP dependencies
    - name: Install PHP dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    # Set up the application
    - name: Set up Laravel application
      run: |
        cp .env.example .env
        php artisan key:generate
        # Add other setup steps as needed

    # Run tests
    - name: Run Laravel tests
      run: php artisan test

    # You can add additional steps for things like linting, code analysis, etc.
